---
- name: making sure sysctl section exists
  lineinfile:
    path: "{{ tuned_profile_dir }}/tuned.conf"
    line: '[sysctl]'
    state: present

- name: adding the hugepages variable to tuned profile
  lineinfile:
    path: "{{ tuned_profile_dir }}/tuned.conf"
    insertafter: '^\[sysctl\]$'
    line: "vm.nr_hugepages = {{ num_of_hugepages }}"
    regexp: "^vm.nr_hugepages"
...
