
- name: "ensure the groups exists"
  group:
    name: "{{ item.pri_group }}"
    state: present
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.pri_group }}"


- name: "creating users" 
  user:
    name: "{{ item.user_name }}"
    password: "{{ item.passwd | password_hash('sha512') }}"
    group: "{{ item.pri_group }}"
    shell: "{{ item.shl }}"
  with_items: "{{ users }}"
  loop_control:
    label: "{{ item.user_name }}"

